### ISSUE TITLE
'dict object' has no attribute 'launch'

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#488]
After updating ansible to 2.1, running on a traditional server, trying to run Paraview

primary job:
```
[17:33:03.124] ERROR: 'dict object' has no attribute 'launch'
  File "cumulus/tasks/job.py", line 278, in submit_job
    script = _generate_submission_script(job, cluster, job_params)
  File "cumulus/tasks/job.py", line 213, in _generate_submission_script
    **job_params)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 63, in top-level template code
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 408, in getattr
    return getattr(obj, attribute)
UndefinedError: 'dict object' has no attribute 'launch'
```

submit pvw job: 
```
[17:33:03.124] ERROR: Exception raise by task.
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "cumulus/taskflow/__init__.py", line 117, in wrapped
    return func(celery_task, *args, **kwargs)
  File "/opt/hpccloud/hpccloud/server/taskflows/hpccloud/taskflow/paraview.py", line 299, in submit_paraview_job
    girder_token=girder_token, monitor=False)
  File "/usr/local/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 439, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "cumulus/tasks/job.py", line 278, in submit_job
    script = _generate_submission_script(job, cluster, job_params)
  File "cumulus/tasks/job.py", line 213, in _generate_submission_script
    **job_params)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 63, in top-level template code
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 408, in getattr
    return getattr(obj, attribute)
UndefinedError: 'dict object' has no attribute 'launch'
```

**Comment by cjh1** [comment]
Fixed by #491
